-- CREATE TABLE CONGRESS_SCHEDULE(
--     meeting_date DATE PRIMARY KEY,
--     get_pdf BOOLEAN NOT NULL DEFAULT FALSE
-- );

-- CREATE TABLE COMMITTEE_SCHEDULE(
--     meeting_date DATE PRIMARY KEY,
--     get_pdf BOOLEAN NOT NULL DEFAULT FALSE
-- );

-- DROP TABLE COMMITTEE_PDF_URL;
-- DROP TABLE CONGRESS_PDF_URL;

-- CREATE TABLE CONGRESS_PDF_URL(
--     meeting_id SERIAL PRIMARY KEY,
--     title VARCHAR(64) NOT NULL,
--     conf_date DATE NOT NULL REFERENCES CONGRESS_SCHEDULE(meeting_date) ON DELETE CASCADE,
--     pdf_url VARCHAR(256),
--     get_pdf BOOLEAN NOT NULL DEFAULT FALSE
-- );

-- CREATE TABLE COMMITTEE_PDF_URL(
--     meeting_id SERIAL PRIMARY KEY,
--     title VARCHAR(64) NOT NULL,
--     conf_date DATE NOT NULL REFERENCES COMMITTEE_SCHEDULE(meeting_date) ON DELETE CASCADE,
--     pdf_url VARCHAR(256),
--     get_pdf BOOLEAN NOT NULL DEFAULT FALSE
-- );




-- SELECT *
-- FROM congress_schedule;

-- SELECT *
-- FROM COMMITTEE_SCHEDULE;

